In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import tree, metrics, model_selection, preprocessing
from sklearn.metrics import confusion_matrix


df = pd.read_csv('/content/iris.csv')
df['species_label'],i = pd.factorize(df['species'])
df['species'].unique()
df['species_label'].unique()

array([0, 1, 2])

In [4]:
y = df['species_label']
x = df[['sepal.length','sepal.width','petal.length','petal.width']]

x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=0)

dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
dtree.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [5]:
y_pred = dtree.predict(x_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy:{:.2f}'.format(accuracy))

Accuracy:0.98


In [6]:
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
